/txt_change_disk_title          "Change Boot Disk"                                   def
/txt_continue                   "Continue"                                           def
/txt_error_title                "I/O Error"                                          def
/txt_exit_dialog                "You are leaving the graphical boot menu [...]"      def
/txt_firmware                   "Firmware Test"                                      def
/txt_info_title                 "Boot Loader"                                        def
/txt_insert_disk                "Insert boot disk %u."                               def
/txt_insert_disk2               "This is boot disk %u."                              def
/txt_insert_disk3               "Insert boot disk %u."                               def
/txt_install                    "Installation"                                       def
/txt_load_kernel                "Loading Linux Kernel"                               def
/txt_load_kernel_title          "Starting..."                                        def
/txt_load_memtest               "Loading memtest86"                                  def
/txt_mediacheck                 "Check Installation Media"                           def
/txt_password                   "Password"                                           def
/txt_password_title             "Password"                                           def
/txt_repain_system              "Repair Installed System"                            def
/txt_rescue                     "Rescue System"                                      def
/txt_safe_linux                 "Linux--Safe Settings"                               def
