/txt_arch                       "Arch"                                               def
/txt_boot_harddisk              "Boot from Hard Disk"                                def
/txt_bootoptions                "Boot Options"                                       def
/txt_cancel                     "Cancel"                                             def
/txt_change_disk_title          "Change Boot Disk"                                   def
/txt_continue                   "Continue"                                           def
/txt_directory                  "Directory"                                          def
/txt_domain                     "Domain"                                             def
/txt_domain_name                "Domain Name"                                        def
/txt_driver_update              "Driver"                                             def
/txt_driver_update2             "Driver Update"                                      def
/txt_dud_download               "Download Driver Update"                             def
/txt_dud_enter_url              "Enter Driver Update URL"                            def
/txt_dud_file_msg               "To load driver updates directly from CD-ROM [...]"  def
/txt_dud_ready                  "Get your driver update floppy ready."               def
/txt_error_title                "I/O Error"                                          def
/txt_exit_dialog                "You are leaving the graphical boot menu [...]"      def
/txt_exit_title                 "Exiting..."                                         def
/txt_file                       "File"                                               def
/txt_firmware                   "Firmware Test"                                      def
/txt_ftp_title                  "FTP Installation"                                   def
/txt_gateway_ip                 "Gateway"                                            def
/txt_harddisk                   "Hard Disk"                                          def
/txt_harddisk_title             "Hard Disk Installation"                             def
/txt_hd_diskdevice              "Disk Device (Scans All Disks If Empty)"             def
/txt_help                       "Help"                                               def
/txt_host_ip                    "Host IP"                                            def
/txt_http_proxy                 "HTTP Proxy"                                         def
/txt_http_title                 "HTTP Installation"                                  def
/txt_info_title                 "Boot Loader"                                        def
/txt_insert_disk                "Insert boot disk %u."                               def
/txt_insert_disk2               "This is boot disk %u."                              def
/txt_insert_disk3               "Insert boot disk %u."                               def
/txt_install                    "Installation"                                       def
/txt_install_source             "Source"                                             def
/txt_kernel                     "Kernel"                                             def
/txt_kernel_default             "Default"                                            def
/txt_kernel_noacpi              "No ACPI"                                            def
/txt_kernel_nolapic             "No Local APIC"                                      def
/txt_kernel_safe                "Safe Settings"                                      def
/txt_keyboard                   "Keyboard"                                           def
/txt_language                   "Language"                                           def
/txt_live_gnome                 "openSUSE Live (GNOME)"                              def
/txt_live_kde                   "openSUSE Live (KDE)"                                def
/txt_load_kernel                "Loading Linux Kernel"                               def
/txt_load_kernel_title          "Starting..."                                        def
/txt_load_memtest               "Loading memtest86"                                  def
/txt_manual_network             "Manual"                                             def
/txt_manual_network_title       "Manual Network Config"                              def
/txt_mediacheck                 "Check Installation Media"                           def
/txt_memtest                    "Memory Test"                                        def
/txt_nameservers                "Nameservers (separated by ',')"                     def
/txt_netmask                    "Netmask"                                            def
/txt_network_config             "Network Config"                                     def
/txt_nfs_title                  "NFS Installation"                                   def
/txt_no                         "No"                                                 def
/txt_no_network                 "No Network"                                         def
/txt_ok                         "Okay"                                               def
/txt_other_options              "Other Options"                                      def
/txt_password                   "Password"                                           def
/txt_password_title             "Password"                                           def
/txt_power_off                  "Halt the system now?"                               def
/txt_power_off_title            "Power Off"                                          def
/txt_reboot                     "Reboot"                                             def
/txt_repain_system              "Repair Installed System"                            def
/txt_rescue                     "Rescue System"                                      def
/txt_safe_linux                 "Linux--Safe Settings"                               def
/txt_server                     "Server"                                             def
/txt_share                      "Share"                                              def
/txt_smb_title                  "SMB (Windows Share) Installation"                   def
/txt_text_mode                  "Text Mode"                                          def
/txt_user1                      "User (Anonymous Login If Empty)"                    def
/txt_user2                      "User (Uses \"guest\" If Empty)"                     def
/txt_video_mode                 "Video Mode"                                         def
/txt_yes                        "Yes"                                                def
/txt_zenAuto                    "Automatic Mode"                                     def
/txt_zenConfig                  "Configure Parameters on ZEN Partition"              def
/txt_zenDisable                 "Disable ZEN Partition"                              def
/txt_zenEnable                  "Enable ZEN Partition"                               def
/txt_zenInstall                 "Install or Update ZEN Partition"                    def
/txt_zenLilo                    "Reinstall ZEN Partition Boot Loader"                def
/txt_zenManual                  "Manual Mode"                                        def
/txt_console                    "Console"                                            def
