% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
%
% Timezones
%
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


/.tz.name   0 def
/.tz.id     1 def

/timezones [
    [ "auto"              ""                               ]
    [ "UTC"               "Etc/UTC utc"                    ]
    [ "Honolulu"          "Pacific/Honolulu"               ]  % GMT-10
    [ "Anchorage*"        "America/Anchorage"              ]  % GMT-9 DST
    [ "Los Angeles*"      "America/Los_Angeles"            ]  % GMT-8 DST
    [ "Phoenix"           "America/Phoenix"                ]  % GMT-7
    [ "Denver*"           "America/Denver"                 ]  % GMT-7 DST
    [ "Managua"           "America/Managua"                ]  % GMT-6
    [ "Chicago*"          "America/Chicago"                ]  % GMT-6 DST
    [ "Bogota"            "America/Bogota"                 ]  % GMT-5
    [ "New York*"         "America/New_York"               ]  % GMT-5 DST
    [ "La Paz"            "America/La_Paz"                 ]  % GMT-4
    [ "Santiago*"         "America/Santiago"               ]  % GMT-4 DST
    [ "Buenos Aires"      "America/Argentina/Buenos_Aires" ]  % GMT-3
    [ "Sao Paulo*"        "America/Sao_Paulo"              ]  % GMT-3 DST
    [ "Casablanca"        "Africa/Casablanca"              ]  % GMT
    [ "London*"           "Europe/London"                  ]  % GMT DST
    [ "Algiers"           "Africa/Algiers"                 ]  % GMT+1
    [ "Berlin*"           "Europe/Berlin"                  ]  % GMT+1 DST
    [ "Johannesburg"      "Africa/Johannesburg"            ]  % GMT+2
    [ "Athens*"           "Europe/Athens"                  ]  % GMT+2 DST
    [ "Baghdad"           "Asia/Baghdad"                   ]  % GMT+3
    [ "Moscow*"           "Europe/Moscow"                  ]  % GMT+3 DST
    [ "Tehran*"           "Asia/Tehran"                    ]  % GMT+330 DST
    [ "Dubai"             "Asia/Dubai"                     ]  % GMT+4
    [ "Baku*"             "Asia/Baku"                      ]  % GMT+4 DST
    [ "Karachi"           "Asia/Karachi"                   ]  % GMT+5
    [ "Yekaterinburg*"    "Asia/Yekaterinburg"             ]  % GMT+5 DST
    [ "Kolkata"           "Asia/Kolkata"                   ]  % GMT+530 % _IN in locales
    [ "Almaty"            "Asia/Almaty"                    ]  % GMT+6 % _BT, _KZ, _KG
    [ "Dhaka*"            "Asia/Dhaka"                     ]  % GMT+6 DST % _BD, _RU
    [ "Bangkok"           "Asia/Bangkok"                   ]  % GMT+7
    [ "Krasnoyarsk*"      "Asia/Krasnoyarsk"               ]  % GMT+7 DST % _RU
    [ "Beijing"           "Asia/Shanghai"                  ]  % GMT+8
    [ "Irkutsk*"          "Asia/Irkutsk"                   ]  % GMT+8 DST % _RU
    [ "Tokyo"             "Asia/Tokyo"                     ]  % GMT+9
    [ "Yakutsk*"          "Asia/Yakutsk"                   ]  % GMT+9 DST % _RU
    [ "Darwin"            "Australia/Darwin"               ]  % GMT+930
    [ "Adelaide*"         "Australia/Adelaide"             ]  % GMT+930 DST
    [ "Brisbane"          "Australia/Brisbane"             ]  % GMT+10
    [ "Sydney*"           "Australia/Sydney"               ]  % GMT+10 DST
    [ "Fiji"              "Pacific/Fiji"                   ]  % GMT+12
    [ "Auckland*"         "Pacific/Auckland"               ]  % GMT+12 DST
    [ "Tongatapu"         "Pacific/Tongatapu"              ]  % GMT+13
] def

